export const APP_EVENTS = {
  openBrowserCredentials: "retainpdf:open-browser-credentials",
  returnHome: "retainpdf:return-home",
  retryStage: "retainpdf:retry-stage",
  homeViewModeChanged: "retainpdf:home-view-mode-changed",
  homeRecentJobsStateChanged: "retainpdf:home-recent-jobs-state-changed",
  statusAreaVisibilityChanged: "retainpdf:status-area-visibility-changed",
  libraryJobCreated: "retainpdf:library-job-created",
  libraryJobUpdated: "retainpdf:library-job-updated",
  libraryRefreshRequested: "retainpdf:library-refresh-requested",
  openTranslationWorkflow: "retainpdf:open-translation-workflow",
  closeTranslationWorkflow: "retainpdf:close-translation-workflow",
  translationWorkflowSync: "retainpdf:translation-workflow-sync",
  submitBusyChanged: "retainpdf:submit-busy-changed",
  refreshGlossaries: "retainpdf:refresh-glossaries",
  openReaderRequested: "retainpdf:open-reader-requested",
};

export const APP_DIALOG_IDS = {
  recentJobs: "query-dialog",
  developerAuth: "developer-auth-dialog",
  developerSettings: "developer-dialog",
  glossaryManager: "glossary-manager-dialog",
  browserCredentials: "browser-credentials-dialog",
  professionalTranslation: "page-range-dialog",
  aiAssistant: "ai-assistant-dialog",
  appSettings: "app-settings-dialog",
  statusDetail: "status-detail-dialog",
  reader: "reader-dialog",
  translationWorkflow: "translation-workflow-dialog",
};

export const APP_SHELL_IDS = {
  fileInput: "file",
  credentialGateAction: "credential-gate-action",
  jobForm: "job-form",
  pageRangeButton: "page-range-btn",
  pageRangeApplyButton: "page-range-apply-btn",
  pageRangeClearButton: "page-range-clear-btn",
  pageRangeStart: "page-range-start",
  pageRangeEnd: "page-range-end",
  cancelButton: "cancel-btn",
  openOutputButton: "open-output-btn",
  errorBox: "error-box",
  libraryAddPdfButton: "library-add-pdf-btn",
  aiAssistantButton: "ai-assistant-btn",
  appSettingsButton: "app-settings-btn",
};

export const APP_DIALOG_BACKDROP_IDS = [
  APP_DIALOG_IDS.recentJobs,
  APP_DIALOG_IDS.developerAuth,
  APP_DIALOG_IDS.developerSettings,
  APP_DIALOG_IDS.glossaryManager,
  APP_DIALOG_IDS.browserCredentials,
  APP_DIALOG_IDS.professionalTranslation,
  APP_DIALOG_IDS.aiAssistant,
  APP_DIALOG_IDS.appSettings,
  APP_DIALOG_IDS.statusDetail,
  APP_DIALOG_IDS.reader,
];
